// Gerado por generate-data.js — não editar manualmente
window.DESPMEN_DATA = {
  "generatedAt": "2026-06-13T02:49:46.429Z",
  "categories": [
    "Aplicação automática",
    "Ateliê e Oficina",
    "Carro",
    "Cartão de crédito",
    "Casa",
    "Compras",
    "Contribuição",
    "Despesa não identificada",
    "Entretenimento",
    "Esportes",
    "Estorno",
    "Fatura",
    "Gatos",
    "Livros",
    "Mercado",
    "Não identificado",
    "Presentes",
    "Receita não identificada",
    "Reembolso",
    "Rendimento",
    "Restaurantes",
    "Saldo",
    "Saque",
    "Saúde",
    "Taxas",
    "Transporte",
    "Viagem"
  ],
  "subcategories": [
    "Água",
    "Aliexpress",
    "Ana Cláudia",
    "Aspirador de pó",
    "Atrativo",
    "Bomboniere",
    "Cog",
    "Combustível",
    "Congelados",
    "Costura",
    "Darf educbank",
    "Delivery",
    "Drogaria",
    "Eletricidade",
    "Erva",
    "Estacionamento",
    "Estadia",
    "Farmácia",
    "Faxina",
    "Fernando",
    "Funilaria",
    "Garagem",
    "Gás",
    "Guia",
    "Ifood",
    "Internet",
    "IPTU",
    "IPVA",
    "Itaucard",
    "Jardim",
    "Kilo",
    "Manuela",
    "Manutenção",
    "Marcelo",
    "Melhoria",
    "Meli/Disney+",
    "Mercadolivre",
    "Mesa",
    "Metrô",
    "Molduras",
    "Nutrição",
    "Passagens",
    "Pedágio",
    "Peixes",
    "Petchef",
    "Piscina",
    "Pizza",
    "Porto Seguro",
    "Prime",
    "Rappi",
    "Redes",
    "Reforma",
    "Rei da Amazônia",
    "Remédios manu reembolsados",
    "Resgate",
    "Restaurante",
    "Safra",
    "Sandra",
    "Segurança",
    "Seguro",
    "Senai",
    "Serralheiro",
    "Shows",
    "Sist Segurança",
    "Spotify",
    "Táxi",
    "Transporte",
    "Uber",
    "Vet",
    "XP",
    "Youtube",
    "Zizi",
    "Zona Azul"
  ],
  "tags": [
    "Antonina2526",
    "Capivara25",
    "Panamá26",
    "Pantanal25",
    "Peru26",
    "Pico do Lopo 26",
    "PiscinaBio",
    "SenacCostura24"
  ],
  "paymentMethods": [
    "Cartão XP",
    "Débito Itaú",
    "Fernando emprestou",
    "Manu emprestou",
    "Pix Itaú"
  ]
};
